src/Entity/Commit.php
<?php

namespace App\Entity;

use App\Repository\CommitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommitRepository::class)
 */
class Commit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_creation;

    /**
     * @ORM\ManyToOne(targetEntity=Blogpost::class, inversedBy="commits")
     */
    private $article;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDateOfCreation(): ?\DateTimeInterface
    {
        return $this->date_of_creation;
    }

    public function setDateOfCreation(\DateTimeInterface $date_of_creation): self
    {
        $this->date_of_creation = $date_of_creation;

        return $this;
    }

    public function getArticle(): ?Blogpost
    {
        return $this->article;
    }

    public function setArticle(?Blogpost $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }
}

src/Form/CommitType.php
<?php

namespace App\Form;

use App\Entity\Commit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pseudo')
            ->add('email')
            ->add('content')
            ->add('save', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commit::class,
        ]);
    }
}

src/Controller/CommitController.php
<?php

namespace App\Controller;

use App\Entity\Commit;
use App\Form\Commit1Type;
use App\Repository\CommitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commit")
 */
class CommitController extends AbstractController
{
    /**
     * @Route("/", name="commit_index", methods={"GET"})
     */
    public function index(CommitRepository $commitRepository): Response
    {
        return $this->render('commit/index.html.twig', [
            'commits' => $commitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="commit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $commit = new Commit();
        $form = $this->createForm(Commit1Type::class, $commit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commit);
            $entityManager->flush();

            return $this->redirectToRoute('commit_index');
        }

        return $this->render('commit/new.html.twig', [
            'commit' => $commit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commit_show", methods={"GET"})
     */
    public function show(Commit $commit): Response
    {
        return $this->render('commit/show.html.twig', [
            'commit' => $commit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commit $commit): Response
    {
        $form = $this->createForm(Commit1Type::class, $commit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commit_index');
        }

        return $this->render('commit/edit.html.twig', [
            'commit' => $commit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Commit $commit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commit_index');
    }
}

templates/commit/_delete_form.html.twig
<form method="post" action="{{ path('commit_delete', {'id': commit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commit{% endblock %}

{% block body %}
    <h1>Edit Commit</h1>

    {{ include('commit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commit_index') }}">back to list</a>

    {{ include('commit/_delete_form.html.twig') }}
{% endblock %}

templates/commit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commit index{% endblock %}

{% block body %}
    <h1>Commit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Content</th>
                <th>Date_of_creation</th>
                <th>Pseudo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commit in commits %}
            <tr>
                <td>{{ commit.id }}</td>
                <td>{{ commit.email }}</td>
                <td>{{ commit.content }}</td>
                <td>{{ commit.dateOfCreation ? commit.dateOfCreation|date('Y-m-d') : '' }}</td>
                <td>{{ commit.pseudo }}</td>
                <td>
                    <a href="{{ path('commit_show', {'id': commit.id}) }}">show</a>
                    <a href="{{ path('commit_edit', {'id': commit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commit_new') }}">Create new</a>
{% endblock %}

templates/commit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commit{% endblock %}

{% block body %}
    <h1>Create new Commit</h1>

    {{ include('commit/_form.html.twig') }}

    <a href="{{ path('commit_index') }}">back to list</a>
{% endblock %}

templates/commit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commit{% endblock %}

{% block body %}
    <h1>Commit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commit.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ commit.email }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ commit.content }}</td>
            </tr>
            <tr>
                <th>Date_of_creation</th>
                <td>{{ commit.dateOfCreation ? commit.dateOfCreation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ commit.pseudo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commit_index') }}">back to list</a>

    <a href="{{ path('commit_edit', {'id': commit.id}) }}">edit</a>

    {{ include('commit/_delete_form.html.twig') }}
{% endblock %}