src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Blogpost::class, mappedBy="author")
     */
    private $blogposts;

    public function __construct()
    {
        $this->blogposts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Blogpost[]
     */
    public function getBlogposts(): Collection
    {
        return $this->blogposts;
    }

    public function addBlogpost(Blogpost $blogpost): self
    {
        if (!$this->blogposts->contains($blogpost)) {
            $this->blogposts[] = $blogpost;
            $blogpost->setAuthor($this);
        }

        return $this;
    }

    public function removeBlogpost(Blogpost $blogpost): self
    {
        if ($this->blogposts->removeElement($blogpost)) {
            // set the owning side to null (unless already changed)
            if ($blogpost->getAuthor() === $this) {
                $blogpost->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;


use App\Entity\Blogpost;
use App\Entity\Commit;
use App\Form\BlogpostType;
use App\Form\CommitType;

use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default")
     */
    public function index(): Response
    {
        $em = $this->getDoctrine()->getRepository(Blogpost::class);




        return $this->render('default/index.html.twig', [
            'articles' => $em->findAll(),
        ]);
    }


    /**
     * @Route("/article/{id}", name="article")
     */
    public function article($id, Request $request): Response
    {
        $emCommit = $this->getDoctrine()->getRepository(Commit::class);

        $emBlogpost = $this->getDoctrine()->getRepository(Blogpost::class);
        $article = $emBlogpost->find($id);

        $commit = new Commit;
        $form = $this->createForm(CommitType::class, $commit);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $commit = $form->getData();
            $commit->setDateOfCreation(new DateTime());
            $commit->setArticle($emBlogpost->find($id));

            $em = $this->getDoctrine()->getManager();
            $em->persist($commit);
            $em->flush();
        }


        return $this->render('default/article.html.twig', [
            "article" =>  $article,
            'form' => $form->createView(),
            "commits" => $emCommit->FindBy(['article' => $article], ['date_of_creation' => 'ASC'], 30)

        ]);
    }

    /**
     * @Route("/newarticle", name="newArticle")
     */
    public function addArticle(Request $request): Response
    {
        $blogpost = new Blogpost;
        $form = $this->createForm(BlogpostType::class, $blogpost);


        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $blogpost = $form->getData();
            $blogpost->setDateOfPublication(new DateTime());
            $blogpost->setAuthor($this->getUser());


            $em = $this->getDoctrine()->getManager();
            $em->persist($blogpost);
            $em->flush();

            return $this->redirectToRoute('/');
        }


        return $this->render('default/formrender.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/default/article.html.twig
{% extends 'base.html.twig' %}


{% block title %}{{article.tittle}}{% endblock %}


{% block body %} 

<style>
.title {margin-left : 8em;
font-size:4em}
.text {margin-left: 5em;
margin-right: 5em;
margin-bottom: 5em;
};
.banner {
    width :100%
    heigh :100em
}
 </style>


{% block content %} 


<img class="banner" src={{article.banner}}>

<h1 class= "title">{{article.tittle}}</h1>


<div class="text"> {{article.content}} 
        <li>ecrit par {{article.author.email}} le {{ article.DateOfPublication|date("d/m/Y")}}
</div>



{{ form(form) }}



    {% for commit in commits  %}
    <h2  > {{commit.pseudo}} a écrit : </h2>
        <li> {{commit.content}}</li>
    {% if app.user.username == article.author.email  %}
    <form><button methods="delete"  href="commit/{{commit.id}}">Delete </button></form>
    {% endif %}

    {% endfor %}

{% endblock %}


{% endblock %}

templates/default/formrender.html.twig
{% extends 'base.html.twig' %}
{% block title %}  Nouvel article{% endblock %}

{% block body %} 


{{ form(form) }}
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .content {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 30ch;
}


</style>
 {% block navbar %} {% endblock %}

<div class="example-wrapper">
    

    {% for article in articles  %}
        <a href='/article/{{article.id}}'> <img  width='300px' height="100px" src= {{article.banner}}> </a>
        <li><a href='/article/{{article.id}}' >{{ article.tittle }} </a></li>
        <li class="content" >{{ article.content }}</li>
        <li>ecrit par {{article.author.email}} le {{ article.DateOfPublication|date("d/m/Y")}}
        </li>

    {% endfor %}

</div>
{% endblock %}